/*
 * Site content. Edit this file to add, reorder or describe projects.
 *
 * Translated text is written { en: '...', fr: '...' }. A plain string is used
 * as is in both languages (titles, names). Interface strings live in i18n.js.
 *
 * Media files are generated by scripts/build-media.sh into assets/media/<slug>/
 * and uploaded to the MinIO bucket "ella". Locally they are served through the
 * src/media symlink.
 */
(function () {
    const isLocal = ['localhost', '127.0.0.1', ''].includes(location.hostname);

    const SHORT = { en: 'Short film', fr: 'Court métrage' };
    const COMMERCIAL = { en: 'Commercial', fr: 'Publicité' };
    const DIRECTOR = { en: 'Director', fr: 'Réalisation' };

    const SITE = {
        // TODO: replace with the public URL of the MinIO bucket (no trailing slash)
        mediaBase: isLocal ? '/media' : 'https://minio.example.com/ella',

        name: 'Ella Couffinhal',
        role: { en: 'Director', fr: 'Réalisatrice' },
        tagline: { en: 'Fiction, commercials & music videos', fr: 'Fiction, publicités & clips' },

        contact: {
            // TODO: fill in real contact details
            email: 'contact@ellacouffinhal.com',
            phone: '',
            instagram: 'https://www.instagram.com/',
            instagramHandle: '@ellacouffinhal',
            vimeo: '',
            city: 'Paris',
        },

        // TODO: rewrite in Ella's own words
        about: {
            en: 'I’m a director. I move between fiction, commercials and music videos with the same care for every shot: a strong image, a sincere emotion and a rhythm that holds until the very last frame.',
            fr: 'Je suis réalisatrice. Je passe de la fiction à la publicité et au clip avec la même exigence pour chaque plan : une image forte, une émotion sincère et un rythme qui tient jusqu’à la dernière seconde.',
        },

        categories: {
            commercials: {
                label: { en: 'Commercials', fr: 'Publicités' },
                blurb: { en: 'The brand films and campaigns I’ve directed.', fr: 'Les films de marque et campagnes que j’ai réalisés.' },
                path: '/commercials/',
            },
            fiction: {
                label: 'Fiction',
                blurb: { en: 'My short films, a series pilot and a documentary.', fr: 'Mes courts métrages, un pilote de série et un documentaire.' },
                path: '/fiction/',
            },
            'music-video': {
                label: { en: 'Music Video', fr: 'Clips' },
                blurb: { en: 'The music videos I’ve directed.', fr: 'Les clips que j’ai réalisés.' },
                path: '/music-video/',
            },
        },

        /*
         * Fields: slug, title, category, type, client (optional), year, duration (seconds),
         * ratio ('16/9', '9/16', '2.39/1'...), description, credits [[role, name]].
         * draft: true hides a project until its media is ready.
         * Empty fields are simply not shown.
         */
        projects: [
            {
                slug: 'nemesis',
                title: 'Némésis',
                category: 'fiction',
                type: SHORT,
                year: '',
                duration: 139,
                ratio: '2.22/1',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'charmail',
                title: 'Charmail',
                category: 'commercials',
                type: COMMERCIAL,
                client: 'Charmail',
                year: '',
                duration: 67,
                ratio: '16/9',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'remanence',
                title: 'Rémanence',
                category: 'fiction',
                type: SHORT,
                year: '',
                duration: 373,
                ratio: '16/9',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'mandat-de-depot',
                title: 'Mandat de dépôt',
                category: 'music-video',
                type: { en: 'Music video', fr: 'Clip' },
                client: 'Lagui feat. Jul',
                year: '',
                duration: 183,
                ratio: '3/2',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'daniel-wellington',
                title: 'Daniel Wellington',
                category: 'commercials',
                type: COMMERCIAL,
                client: 'Daniel Wellington',
                year: '',
                duration: 41,
                ratio: '9/16',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'l-ombre-des-champs',
                title: "L'Ombre des champs",
                category: 'fiction',
                type: { en: 'Series pilot', fr: 'Pilote de série' },
                year: '',
                duration: 955,
                ratio: '2.2/1',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'contre-soiree',
                title: 'Contre-soirée',
                category: 'fiction',
                type: SHORT,
                year: '',
                duration: 560,
                ratio: '2.35/1',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'les-magnetiques',
                title: 'Les Magnétiques',
                category: 'fiction',
                type: SHORT,
                year: '',
                duration: 413,
                ratio: '16/9',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },
            {
                slug: 'le-caprice',
                title: 'Le Caprice',
                category: 'fiction',
                type: { en: 'Documentary — teaser', fr: 'Documentaire — teaser' },
                year: '',
                duration: 58,
                ratio: '16/9',
                description: { en: '', fr: '' },
                credits: [[DIRECTOR, 'Ella Couffinhal']],
            },

            // Coming soon: add the media then remove draft
            { slug: 'babybel', title: 'Babybel', category: 'commercials', type: COMMERCIAL, client: 'Babybel', ratio: '16/9', draft: true },
            { slug: 'maraude', title: 'Maraude', category: 'commercials', type: COMMERCIAL, client: 'Le Cœur sur la main', ratio: '16/9', draft: true },
            { slug: 'ugly-privilege', title: 'Ugly Privilege', category: 'fiction', type: SHORT, ratio: '16/9', draft: true },
        ],

        // Home page mosaic, in order (6-column grid, see css .mosaic)
        featured: ['nemesis', 'daniel-wellington', 'le-caprice', 'charmail', 'mandat-de-depot'],

        /*
         * Festival selections and awards.
         * { year: '2025', festival: 'Festival name', city: 'City', film: 'slug',
         *   award: { en: 'Official selection', fr: 'Sélection officielle' } }
         */
        festivals: [],
    };

    // Everything below uses the text of the current language only
    const S = (window.SITE = I18N.localize(SITE));
    S.visibleProjects = S.projects.filter((p) => !p.draft);
    S.bySlug = (slug) => S.visibleProjects.find((p) => p.slug === slug);
    S.media = (slug, file) => `${S.mediaBase}/${slug}/${file}`;

    // Credit-style runtime, e.g. 6′13″
    S.projects.forEach((p) => {
        if (p.duration && !p.runtime) p.runtime = `${Math.floor(p.duration / 60)}′${String(Math.round(p.duration % 60)).padStart(2, '0')}″`;
    });
})();
